<?php

namespace HVG\SystemBundle\Entity;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastByCommunity(Community $community = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('l');
        $qb->select('l')
            ->from('HVGSystemBundle:AccessLog', 'l')
            ->join('l.checkpoint', 'lp')
            ->orderBy('l.createdAt', 'DESC')
            ->where('lp.community = :community')
            ->setParameters(array('community' => $community))
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByCommunity($community, $sort, $direction)
    {
        return $this->getEntityManager()->createQueryBuilder('l')
            ->select('l')
            ->from('HVGSystemBundle:AccessLog', 'l')
            ->join('l.checkpoint', 'lp')
            ->where('lp.community = :community')
            ->orderBy('l.'.$sort, $direction)
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }

}
