<?php

namespace HVG\SystemBundle\Entity;

/**
 * AccessGateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessGateRepository extends \Doctrine\ORM\EntityRepository
{
}
