<?php

namespace HVG\SystemBundle\Entity;

/**
 * AccessPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
