<?php

namespace HVG\SystemBundle\Entity;

/**
 * AllowanceChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowanceChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
