<?php

namespace HVG\SystemBundle\Entity;

/**
 * BankAccountKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountKindRepository extends \Doctrine\ORM\EntityRepository
{
}
