<?php

namespace HVG\SystemBundle\Entity;

/**
 * BankAccountTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
