<?php

namespace HVG\SystemBundle\Entity;

/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends \Doctrine\ORM\EntityRepository
{
}
