<?php

namespace HVG\SystemBundle\Entity;

/**
 * CarparkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarparkRepository extends \Doctrine\ORM\EntityRepository
{
}
