<?php

namespace HVG\SystemBundle\Entity;

/**
 * CheckpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckpointRepository extends \Doctrine\ORM\EntityRepository
{
}
