<?php

namespace HVG\SystemBundle\Entity;

/**
 * CommunicationChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationChannelRepository extends \Doctrine\ORM\EntityRepository
{
}
