<?php

namespace HVG\SystemBundle\Entity;

/**
 * CommunityStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
