<?php

namespace HVG\SystemBundle\Entity;

/**
 * CommunityEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCommunity($community, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('e')
            ->select('e', 'c')
            ->from('HVGSystemBundle:CommunityEvent', 'e')
            ->join('e.community', 'c')
            ->where('c.id = :community')
            ->orderBy('e.'.$sort, $direction)
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findValidByCommunity($community)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('e')
            ->select('e', 'c')
            ->from('HVGSystemBundle:CommunityEvent', 'e')
            ->join('e.community', 'c')
            ->where('c.id = :community')
            ->andWhere('e.startedAt < :now')
            ->andWhere('e.finnishedAt > :now')
            ->setParameters(array('community' => $community, 'now' => new \DateTime()))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByUnit($unit)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('e')
            ->select('e', 'u', 'c')
            ->from('HVGSystemBundle:CommunityEvent', 'e')
            ->join('e.community', 'c')
            ->join('e.units', 'u')
//            ->where('u.id = :unit')
//            ->setParameters(array('unit' => $unit))
            ->where('c.id = :community')
            ->setParameters(array('community' => $unit->getCommunity()))
            ->getQuery()
            ->getResult()
        ;
    }
}
