<?php

namespace HVG\SystemBundle\Entity;

/**
 * ContactKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactKindRepository extends \Doctrine\ORM\EntityRepository
{
}
