<?php

namespace HVG\SystemBundle\Entity;

use HVG\SystemBundle\Entity\Community;
use HVG\SystemBundle\Entity\UnitGroup;
use HVG\SystemBundle\Entity\Unit;
/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastByUnit(Unit $unit = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('g');
        $qb->select('g', 'gp', 'gcp', 'gg', 'gc')
            ->from('HVGSystemBundle:Guest', 'g')
            ->leftJoin('g.people', 'gp')
            ->leftJoin('g.guestcarpark', 'gcp')
            ->leftJoin('g.accessguard', 'gg')
            ->leftJoin('g.checkpoint', 'gc')
            ->orderBy('g.createdAt', 'DESC')
            ->where('g.unit = :unit')
            ->andWhere('g.createdAt > :datetime')
            ->setParameters(array('unit' => $unit, 'datetime' => new \DateTime('-48 hours')))
        ;
        return $qb->getQuery()->getResult();
    }

    public function getLastByUnitgroup(UnitGroup $unitgroup = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('g');
        $qb->select('g', 'gp', 'gcp', 'gg', 'gc')
            ->from('HVGSystemBundle:Guest', 'g')
            ->join('g.unit', 'gu')
            ->leftJoin('g.people', 'gp')
            ->leftJoin('g.guestcarpark', 'gcp')
            ->leftJoin('g.accessguard', 'gg')
            ->leftJoin('g.checkpoint', 'gc')
            ->orderBy('g.createdAt', 'DESC')
            ->where('gu.unitgroup = :unitgroup')
            ->andWhere('g.createdAt > :datetime')
            ->setParameters(array('unitgroup' => $unitgroup, 'datetime' => new \DateTime('-48 hours')))
        ;
        return $qb->getQuery()->getResult();
    }

    public function getLastByCommunity(Community $community = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('g');
        $qb->select('g', 'gp', 'gcp', 'gg', 'gc')
            ->from('HVGSystemBundle:Guest', 'g')
            ->join('g.unit', 'gu')
            ->leftJoin('g.people', 'gp')
            ->leftJoin('g.guestcarpark', 'gcp')
            ->leftJoin('g.accessguard', 'gg')
            ->leftJoin('g.checkpoint', 'gc')
            ->orderBy('g.createdAt', 'DESC')
            ->where('gu.community = :community')
            ->andWhere('g.createdAt > :datetime')
            ->setParameters(array('community' => $community, 'datetime' => new \DateTime('-48 hours')))
        ;
        return $qb->getQuery()->getResult();
    }

    public function findBySearch($community, $search)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('g', 'gu', 'guc')
            ->select('g', 'gu', 'gp')
            ->from('HVGSystemBundle:Guest', 'g')
            ->leftJoin('g.unit', 'gu')
            ->leftJoin('g.people', 'gp')
            ->leftJoin('gu.community', 'guc')
            ->andWhere('g.carLicence LIKE :search')
            ->orWhere('gp.name LIKE :search')
            ->andWhere('guc.id = :community')
            ->setParameters(array('community' => $community, 'search' => '%'.$search.'%'))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByUnit($unit, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g', 'gu')
            ->from('HVGSystemBundle:Guest', 'g')
            ->join('g.unit', 'gu')
            ->where('g.unit = :unit')
            ->orderBy('g.'.$sort, $direction)
            ->setParameters(array('unit' => $unit))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByUnitgroup($unitgroup, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g', 'gu')
            ->from('HVGSystemBundle:Guest', 'g')
            ->join('g.unit', 'gu')
            ->join('gu.unitgroup', 'gug')
            ->where('gug.id = :unitgroup')
            ->orderBy('g.'.$sort, $direction)
            ->setParameters(array('unitgroup' => $unitgroup))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByCommunity($community, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g', 'gu')
            ->from('HVGSystemBundle:Guest', 'g')
            ->join('g.unit', 'gu')
            ->join('gu.community', 'guc')
            ->where('guc.id = :community')
            ->orderBy('g.'.$sort, $direction)
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }
}
