<?php

namespace HVG\SystemBundle\Entity;

/**
 * GuestCarparkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestCarparkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCommunity($community, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g', 'c')
            ->from('HVGSystemBundle:GuestCarpark', 'g')
            ->join('g.community', 'c')
            ->where('c.id = :community')
            ->orderBy('g.'.$sort, $direction)
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }
}
