<?php

namespace HVG\SystemBundle\Entity;

/**
 * GuestCarparkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestCarparkRepository extends \Doctrine\ORM\EntityRepository
{
}
