<?php

namespace HVG\SystemBundle\Entity;

/**
 * InflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InflowRepository extends \Doctrine\ORM\EntityRepository
{
}
