<?php

namespace HVG\SystemBundle\Entity;

/**
 * OutflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutflowRepository extends \Doctrine\ORM\EntityRepository
{
}
