<?php

namespace HVG\SystemBundle\Entity;

/**
 * PayOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
