<?php

namespace HVG\SystemBundle\Entity;

/**
 * PersonProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
