<?php

namespace HVG\SystemBundle\Entity;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchByRut($rut)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('p');
        $qb->select('p.rut, p.name')
            ->from('HVGSystemBundle:Person', 'p')
            ->where('p.rut LIKE :rut')
            ->setParameter('rut', '%'.$rut.'%');
        return $qb->getQuery()->getArrayResult();
    }
}
