<?php

namespace HVG\SystemBundle\Entity;

/**
 * PetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionRepository extends \Doctrine\ORM\EntityRepository
{
}
