<?php

namespace HVG\SystemBundle\Entity;

/**
 * PetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMy($areas, $communities)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('p')
            ->select('p')
            ->from('HVGSystemBundle:Petition', 'p')
            ->where('p.area IN (:areas)')
            ->andWhere('p.community IN (:communities)')
            ->setParameters(array('areas' => $areas, 'communities' => $communities))
            ->getQuery()
            ->getResult();
    }
}
