<?php

namespace HVG\SystemBundle\Entity;

/**
 * PetitionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
