<?php

namespace HVG\SystemBundle\Entity;

/**
 * ProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
