<?php

namespace HVG\SystemBundle\Entity;

/**
 * ProjectProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectProposalRepository extends \Doctrine\ORM\EntityRepository
{
}
