<?php

namespace HVG\SystemBundle\Entity;

/**
 * ProviderServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
