<?php

namespace HVG\SystemBundle\Entity;

/**
 * ProviderAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
