<?php

namespace HVG\SystemBundle\Entity;

/**
 * ProviderStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
