<?php

namespace HVG\SystemBundle\Entity;

/**
 * RequirementCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
