<?php

namespace HVG\SystemBundle\Entity;

/**
 * RequirementStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
