<?php

namespace HVG\SystemBundle\Entity;

/**
 * RequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderByStatus()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
            ->select('r')
            ->from('HVGSystemBundle:Requirement', 'r')
            ->leftJoin('r.status', 's')
            ->orderBy('s.id', 'ASC')
            ->getQuery()
            ->getResult();
    }

}
