<?php

namespace HVG\SystemBundle\Entity;

/**
 * RequirementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
