<?php

namespace HVG\SystemBundle\Entity;

/**
 * ServiceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastByCommunity(Community $community = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('l');
        $qb->select('l')
            ->from('HVGSystemBundle:ServiceLog', 'l')
            ->join('l.service', 'ls')
            ->orderBy('l.createdAt', 'DESC')
            ->where('ls.community = :community')
            ->setParameters(array('community' => $community))
        ;
        return $qb->getQuery()->getResult();
    }

}
