<?php

namespace HVG\SystemBundle\Entity;

/**
 * ServiceAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
