<?php

namespace HVG\SystemBundle\Entity;

/**
 * SupervisorsLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupervisorsLogRepository extends \Doctrine\ORM\EntityRepository
{
}
