<?php

namespace HVG\SystemBundle\Entity;

/**
 * TestingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestingRepository extends \Doctrine\ORM\EntityRepository
{
}
