<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitResidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitResidentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNameByUnit($unit)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('r')
            ->select('r.name')
            ->from('HVGSystemBundle:UnitResident', 'r')
            ->where('r.unit = :unit')
            ->setParameters(array('unit' => $unit))
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
