<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUnitGroup($unit)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('r')
            ->select('r.name, r.phone')
            ->from('HVGSystemBundle:UnitResident', 'r')
            ->where('r.unit = :unit')
            ->setParameters(array('unit' => $unit))
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
