<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitResidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitResidentRepository extends \Doctrine\ORM\EntityRepository
{
}
