<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitInsurancePolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitInsurancePolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
