<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitMemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitMemoRepository extends \Doctrine\ORM\EntityRepository
{
}
