<?php

namespace HVG\SystemBundle\Entity;

/**
 * UnitGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
