<?php

namespace HVG\SystemBundle\Entity;

/**
 * WarehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUnitgroup($unitgroup)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w')
            ->from('HVGSystemBundle:Warehouse', 'w')
            ->join('w.unit', 'wu')
            ->join('wu.unitgroup', 'wuu')
            ->where('wuu.id = :unitgroup')
            ->setParameters(array('unitgroup' => $unitgroup))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByCommunity($community)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w')
            ->from('HVGSystemBundle:Warehouse', 'w')
            ->join('w.unit', 'wu')
            ->join('wu.community', 'wuc')
            ->where('wuc.id = :community')
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }
}
