<?php

namespace HVG\SystemBundle\Entity;

/**
 * WarehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUnit($unit, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w', 'wu')
            ->from('HVGSystemBundle:Warehouse', 'w')
            ->join('w.unit', 'wu')
            ->where('w.unit = :unit')
            ->orderBy('w.'.$sort, $direction)
            ->setParameters(array('unit' => $unit))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByUnitgroup($unitgroup, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w', 'wu')
            ->from('HVGSystemBundle:Warehouse', 'w')
            ->join('w.unit', 'wu')
            ->join('wu.unitgroup', 'wug')
            ->where('wug.id = :unitgroup')
            ->orderBy('w.'.$sort, $direction)
            ->setParameters(array('unitgroup' => $unitgroup))
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByCommunity($community, $sort, $direction)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w', 'wu')
            ->from('HVGSystemBundle:Warehouse', 'w')
            ->join('w.unit', 'wu')
            ->join('wu.community', 'wuc')
            ->where('wuc.id = :community')
            ->orderBy('w.'.$sort, $direction)
            ->setParameters(array('community' => $community))
            ->getQuery()
            ->getResult()
        ;
    }
}
