public_pet_new:
    path:     /{hash}/new
    defaults: { _controller: "HVGPublicBundle:Pet:new" }
    methods:  [GET, POST]

public_pet_test:
    path:     /test
    defaults: { _controller: "HVGPublicBundle:Pet:test" }
    methods:  [GET, POST]

