accesscontrol_accessguard_index:
    path:     /{hash}/{checkpoint}
    defaults: { _controller: "HVGAccessControlBundle:AccessGuard:index" }
    methods:  GET

accesscontrol_accessguard_change:
    path:     /{hash}/{checkpoint}/{accessguard}/change
    defaults: { _controller: "HVGAccessControlBundle:AccessGuard:change" }
    methods:  GET
