# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

#    access_denied_url:    ~
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [hvg_userbundle]
#                providers: [in_memory, hvg_userbundle]
#        in_memory: 
#            memory:
#                users:
#                    root: { password: Au0ZedG4Ewn5aOK, roles: 'ROLE_ADMIN' }
#                    admin: { password: admin, roles: 'ROLE_ADMIN' }
        hvg_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: /login
                failure_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /agent
                csrf_token_generator: security.csrf.token_manager
                failure_path: /login
            logout:
                path:   /logout
                target: /login

    access_denied_url: /agent/error/403
    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/resetting, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/agent, roles: [ROLE_AGENT] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/system, roles: [ROLE_ADMIN] }
        - { path: ^/user, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
