# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - :Form:bootstrap.html.twig
            - :Form:fileinput.html.twig
            - :Form:entitytable.html.twig
            - :Form:prototype.html.twig

    globals:
        ticketstatuses:
            1: Nuevo
            2: Asignado
            3: En Progreso
            4: Pendiente
            5: Resuelto
            6: Cerrado
        petgroups:
            1: Canino
            2: Felino
            3: Ave
            4: Pez
            5: Exótico
        petgenders:
            m: Macho
            h: Hembra
            c: Macho Castrado
            e: Hembra Esterilizada
            s: Sin sexar
        petcolors:
            1: Negro
            2: Blanco
            3: Café
            4: Gris
            5: Blanco y negro
            6: Blanco y café
            7: Otro
