# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - :Form:bootstrap.html.twig
            - :Form:fileinput.html.twig
            - :Form:entitytable.html.twig
            - :Form:prototype.html.twig

    globals:
        ticketstatuses: %ticketstatuses%
        petgroups: %petgroups%
        petgenders: %petgenders%
        petcolors: %petcolors%
