services:
#    hvg_exchange.example:
#        class: HVG\ExchangeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    hvg_exchange.form.type.ticketstatus:
        class: HVG\ExchangeBundle\Form\Type\TicketStatusType
        arguments: ["%ticketstatuses%"]
        tags:
            - { name: form.type }
