HVG\SystemBundle\Entity\BankAccount:
    type: entity
    table: BankAccount
    repositoryClass: HVG\SystemBundle\Entity\BankAccountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        bank:
            targetEntity: HVG\SystemBundle\Entity\Bank
        bankAccountType:
            targetEntity: HVG\SystemBundle\Entity\BankAccountType
        provider:
            targetEntity: HVG\SystemBundle\Entity\Provider
    fields:
        rut:
            type: string
            length: 10
            nullable: true
        name:
            type: string
            length: 100
            nullable: true
        number:
            type: string
            length: 20
            nullable: true
        mail:
            type: string
            length: 30
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }