HVG\SystemBundle\Entity\BankAccount:
    type: entity
    table: BankAccount
    repositoryClass: HVG\SystemBundle\Entity\BankAccountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        bank:
            targetEntity: HVG\SystemBundle\Entity\Bank
        bank_account_kind:
            targetEntity: HVG\SystemBundle\Entity\BankAccountKind
        provider:
            targetEntity: HVG\SystemBundle\Entity\Provider
            inversedBy: bank_accounts
    fields:
        ncuenta:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }