HVG\SystemBundle\Entity\CommunicationChannel:
    type: entity
    table: CommunicationChannel
    repositoryClass: HVG\SystemBundle\Entity\CommunicationChannelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        requirements:
            targetEntity: HVG\SystemBundle\Entity\Requirement
            mappedBy: channel
    fields:
        name:
            type: string
            length: 100
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }