HVG\SystemBundle\Entity\ContactPerson:
    type: entity
    table: ContactPerson
    repositoryClass: HVG\SystemBundle\Entity\ContactPersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        person:
            targetEntity: HVG\SystemBundle\Entity\Person
            inversedBy: contacts_person
    fields:
        phone:
            type: string
            length: 300
            nullable: true
        email:
            type: string
            length: 300
            nullable: true
        address:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }