HVG\SystemBundle\Entity\Contact:
    type: entity
    table: Contact
    repositoryClass: HVG\SystemBundle\Entity\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        person:
            targetEntity: HVG\SystemBundle\Entity\Person
            inversedBy: contacts
    fields:
        name:
            type: string
            length: 300
        phone:
            type: string
            length: 300
            nullable: true
        email:
            type: string
            length: 300
            nullable: true
        address:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }