HVG\SystemBundle\Entity\Expenditure:
    type: entity
    table: Expenditure
    repositoryClass: HVG\SystemBundle\Entity\ExpenditureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        community:
            targetEntity: HVG\SystemBundle\Entity\Community
            inversedBy: expenditures
        outflow:
            targetEntity: HVG\SystemBundle\Entity\Outflow
            inversedBy: expenditures
    oneToMany:
        items:
            targetEntity: HVG\SystemBundle\Entity\Item
            mappedBy: expenditure
            cascade: ["persist", "merge"]
    fields:
        name:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }