HVG\SystemBundle\Entity\Payment:
    type: entity
    table: Payment
    repositoryClass: HVG\SystemBundle\Entity\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        expenditures:
            targetEntity: HVG\SystemBundle\Entity\Expenditure
            mappedBy: payment
    manyToOne:
        community:
            targetEntity: HVG\SystemBundle\Entity\Community
            inversedBy: payments
    fields:
        name:
            type: string
            length: 100
            nullable: true
        amount:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }