HVG\SystemBundle\Entity\PayOrder:
    type: entity
    table: PayOrder
    repositoryClass: HVG\SystemBundle\Entity\PayOrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        provider:
            targetEntity: HVG\SystemBundle\Entity\Provider
        community:
            targetEntity: HVG\SystemBundle\Entity\Community
        agent:
            targetEntity: HVG\SystemBundle\Entity\Agent
    fields:
        totalPrice:
            type: integer
            nullable: true
        finishedDate:
            type: date
            nullable: true
        description:
            type: text
            length: 300
            nullable: true
        documentLink:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }