HVG\SystemBundle\Entity\PersonProvider:
    type: entity
    table: PersonProvider
    repositoryClass: HVG\SystemBundle\Entity\PersonProviderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        person:
            targetEntity: HVG\SystemBundle\Entity\Person
        provider:
            targetEntity: HVG\SystemBundle\Entity\Provider
    fields:
        position:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }