HVG\SystemBundle\Entity\PetitionAction:
    type: entity
    table: PetitionAction
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        petition:
            targetEntity: HVG\SystemBundle\Entity\Petition
            inversedBy: petitionactions
        user:
            targetEntity: HVG\UserBundle\Entity\User
            inversedBy: petitionactions
    fields:
        description:
            type: string
            length: 300
            nullable: true
        filename:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }