HVG\SystemBundle\Entity\ProcessAction:
    type: entity
    table: ProcessAction
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        process:
            targetEntity: HVG\SystemBundle\Entity\Process
            inversedBy: actions
    fields:
        description:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }