HVG\SystemBundle\Entity\Provider:
    type: entity
    table: Provider
    repositoryClass: HVG\SystemBundle\Entity\ProviderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        service:
            targetEntity: HVG\SystemBundle\Entity\Service
            inversedBy: providers
    fields:
        name:
            type: string
            length: 300
            nullable: true
        rut:
            type: string
            length: 20
            nullable: true
        contact_phone:
            type: string
            length: 20
            nullable: true
        contact_email:
            type: string
            length: 50
            nullable: true
        contact_name:
            type: string
            length: 300
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }