HVG\SystemBundle\Entity\Provider:
    type: entity
    table: Provider
    repositoryClass: HVG\SystemBundle\Entity\ProviderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        person:
            targetEntity: HVG\SystemBundle\Entity\Person
    manyToOne:
        providerservice:
            targetEntity: HVG\SystemBundle\Entity\ProviderService
            inversedBy: providers
    oneToMany:
        providerstaff:
            targetEntity: HVG\SystemBundle\Entity\ProviderStaff
            mappedBy: provider
        provideraccounts:
            targetEntity: HVG\SystemBundle\Entity\ProviderAccount
            mappedBy: provider
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }