HVG\SystemBundle\Entity\Request:
    type: entity
    table: Request
    repositoryClass: HVG\SystemBundle\Entity\RequestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        request_status:
            targetEntity: HVG\SystemBundle\Entity\RequestStatus
            inversedBy: requests
        community:
            targetEntity: HVG\SystemBundle\Entity\Community
            inversedBy: requests
        area:
            targetEntity: HVG\SystemBundle\Entity\Area
            inversedBy: requests
        agent:
            targetEntity: HVG\SystemBundle\Entity\Agent
            inversedBy: requests
    oneToMany:
        request_actions:
            targetEntity: HVG\SystemBundle\Entity\RequestAction
            mappedBy: request
        request_evaluations:
            targetEntity: HVG\SystemBundle\Entity\RequestEvaluation
            mappedBy: request
    fields:
        description:
            type: string
            length: 300
            nullable: true
        expiry:
            type: datetime
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
