HVG\SystemBundle\Entity\RequirementComment:
    type: entity
    table: RequirementComment
    repositoryClass: HVG\SystemBundle\Entity\RequirementCommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        requirement:
            targetEntity: HVG\SystemBundle\Entity\Requirement
            inversedBy: comment
    fields:
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }