HVG\SystemBundle\Entity\RequestEvaluation:
    type: entity
    table: RequestEvaluation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        request:
            targetEntity: HVG\SystemBundle\Entity\Request
            inversedBy: request_evaluations
        agent:
            targetEntity: HVG\SystemBundle\Entity\Agent
            inversedBy: request_evaluations
    fields:
        value:
            type: integer
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }