HVG\SystemBundle\Entity\Requirement:
    type: entity
    table: Requirement
    repositoryClass: HVG\SystemBundle\Entity\RequirementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        creator:
            targetEntity: HVG\SystemBundle\Entity\Agent
        carrier:
            targetEntity: HVG\SystemBundle\Entity\Agent
            inversedBy: requirements
        status:
            targetEntity: HVG\SystemBundle\Entity\RequirementStatus
            inversedBy: requirements
        channel:
            targetEntity: HVG\SystemBundle\Entity\CommunicationChannel
            inversedBy: requirements
        community:
            targetEntity: HVG\SystemBundle\Entity\Community
            inversedBy: requirements
    oneToMany:
        comments:
            targetEntity: HVG\SystemBundle\Entity\RequirementComment
            mappedBy: requirements
    fields:
        issue:
            type: string
            length: 300
            nullable: true
        committal:
            type: date
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
