HVG\SystemBundle\Entity\ServiceLog:
    type: entity
    table: ServiceLog
    repositoryClass: HVG\SystemBundle\Entity\ServiceLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        service:
            targetEntity: HVG\SystemBundle\Entity\Service
            inversedBy: servicelogs
        serviceagent:
            targetEntity: HVG\SystemBundle\Entity\ServiceAgent
            inversedBy: servicelogs
    fields:
        description:
            type: text
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    lifecycleCallbacks: {  }