HVG\SystemBundle\Entity\UnitLog:
    type: entity
    table: UnitLog
    repositoryClass: HVG\SystemBundle\Entity\UnitLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        unit:
            targetEntity: HVG\SystemBundle\Entity\Unit
            inversedBy: logs
    fields:
        description:
            type: text
        expiredAt:
            type: date
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }