agent_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Agent:index" }
    methods:  GET

agent_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Agent:show" }
    methods:  GET

agent_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Agent:new" }
    methods:  [GET, POST]

agent_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Agent:edit" }
    methods:  [GET, POST]

agent_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Agent:delete" }
    methods:  DELETE
