allowancecharge_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:AllowanceCharge:index" }
    methods:  GET

allowancecharge_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:AllowanceCharge:show" }
    methods:  GET

allowancecharge_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:AllowanceCharge:new" }
    methods:  [GET, POST]

allowancecharge_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:AllowanceCharge:edit" }
    methods:  [GET, POST]

allowancecharge_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:AllowanceCharge:delete" }
    methods:  DELETE
