bank_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Bank:index" }
    methods:  GET

bank_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Bank:show" }
    methods:  GET

bank_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Bank:new" }
    methods:  [GET, POST]

bank_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Bank:edit" }
    methods:  [GET, POST]

bank_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Bank:delete" }
    methods:  DELETE
