bankaccountkind_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:BankAccountKind:index" }
    methods:  GET

bankaccountkind_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:BankAccountKind:show" }
    methods:  GET

bankaccountkind_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:BankAccountKind:new" }
    methods:  [GET, POST]

bankaccountkind_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:BankAccountKind:edit" }
    methods:  [GET, POST]

bankaccountkind_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:BankAccountKind:delete" }
    methods:  DELETE
