bankaccount_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:BankAccount:index" }
    methods:  GET

bankaccount_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:BankAccount:show" }
    methods:  GET

bankaccount_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:BankAccount:new" }
    methods:  [GET, POST]

bankaccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:BankAccount:edit" }
    methods:  [GET, POST]

bankaccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:BankAccount:delete" }
    methods:  DELETE
