building_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Building:index" }
    methods:  GET

building_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Building:show" }
    methods:  GET

building_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Building:new" }
    methods:  [GET, POST]

building_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Building:edit" }
    methods:  [GET, POST]

building_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Building:delete" }
    methods:  DELETE
