contactperson_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:ContactPerson:index" }
    methods:  GET

contactperson_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:ContactPerson:show" }
    methods:  GET

contactperson_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:ContactPerson:new" }
    methods:  [GET, POST]

contactperson_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:ContactPerson:edit" }
    methods:  [GET, POST]

contactperson_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:ContactPerson:delete" }
    methods:  DELETE
