expenditure_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Expenditure:index" }
    methods:  GET

expenditure_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Expenditure:show" }
    methods:  GET

expenditure_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Expenditure:new" }
    methods:  [GET, POST]

expenditure_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Expenditure:edit" }
    methods:  [GET, POST]

expenditure_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Expenditure:delete" }
    methods:  DELETE
