fund_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Fund:index" }
    methods:  GET

fund_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Fund:show" }
    methods:  GET

fund_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Fund:new" }
    methods:  [GET, POST]

fund_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Fund:edit" }
    methods:  [GET, POST]

fund_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Fund:delete" }
    methods:  DELETE
