guest_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Guest:index" }
    methods:  GET

guest_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Guest:show" }
    methods:  GET

guest_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Guest:new" }
    methods:  [GET, POST]

guest_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Guest:edit" }
    methods:  [GET, POST]

guest_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Guest:delete" }
    methods:  DELETE
