payment_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Payment:index" }
    methods:  GET

payment_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Payment:show" }
    methods:  GET

payment_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Payment:new" }
    methods:  [GET, POST]

payment_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Payment:edit" }
    methods:  [GET, POST]

payment_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Payment:delete" }
    methods:  DELETE
