pay_order_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:PayOrder:index" }
    methods:  GET

pay_order_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:PayOrder:show" }
    methods:  GET

pay_order_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:PayOrder:new" }
    methods:  [GET, POST]

pay_order_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:PayOrder:edit" }
    methods:  [GET, POST]

pay_order_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:PayOrder:delete" }
    methods:  DELETE
