petition_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Petition:index" }
    methods:  GET

petition_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Petition:show" }
    methods:  GET

petition_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Petition:new" }
    methods:  [GET, POST]

petition_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Petition:edit" }
    methods:  [GET, POST]

petition_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Petition:delete" }
    methods:  DELETE
