petitionstatus_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:PetitionStatus:index" }
    methods:  GET

petitionstatus_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:PetitionStatus:show" }
    methods:  GET

petitionstatus_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:PetitionStatus:new" }
    methods:  [GET, POST]

petitionstatus_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:PetitionStatus:edit" }
    methods:  [GET, POST]

petitionstatus_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:PetitionStatus:delete" }
    methods:  DELETE
