projectaction_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:ProjectAction:index" }
    methods:  GET

projectaction_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:ProjectAction:show" }
    methods:  GET

projectaction_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:ProjectAction:new" }
    methods:  [GET, POST]

projectaction_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:ProjectAction:edit" }
    methods:  [GET, POST]

projectaction_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:ProjectAction:delete" }
    methods:  DELETE
