projectproposal_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:ProjectProposal:index" }
    methods:  GET

projectproposal_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:ProjectProposal:show" }
    methods:  GET

projectproposal_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:ProjectProposal:new" }
    methods:  [GET, POST]

projectproposal_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:ProjectProposal:edit" }
    methods:  [GET, POST]

projectproposal_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:ProjectProposal:delete" }
    methods:  DELETE
