provideraccount_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:ProviderAccount:index" }
    methods:  GET

provideraccount_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:ProviderAccount:show" }
    methods:  GET

provideraccount_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:ProviderAccount:new" }
    methods:  [GET, POST]

provideraccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:ProviderAccount:edit" }
    methods:  [GET, POST]

provideraccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:ProviderAccount:delete" }
    methods:  DELETE
