requirement_comment_new:
    path:     /{id}/new
    defaults: { _controller: "HVGSystemBundle:RequirementComment:new" }
    methods:  [GET, POST]

requirement_comment_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:RequirementComment:edit" }
    methods:  [GET, POST]

requirement_comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:RequirementComment:delete" }
    methods:  DELETE
