requirement_type_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:RequirementType:index" }
    methods:  GET

requirement_type_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:RequirementType:show" }
    methods:  GET

requirement_type_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:RequirementType:new" }
    methods:  [GET, POST]

requirement_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:RequirementType:edit" }
    methods:  [GET, POST]

requirement_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:RequirementType:delete" }
    methods:  DELETE
