supervisorslog_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:SupervisorsLog:index" }
    methods:  GET

supervisorslog_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:SupervisorsLog:show" }
    methods:  GET

supervisorslog_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:SupervisorsLog:new" }
    methods:  [GET, POST]

supervisorslog_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:SupervisorsLog:edit" }
    methods:  [GET, POST]

supervisorslog_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:SupervisorsLog:delete" }
    methods:  DELETE
