ticketaction_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:TicketAction:index" }
    methods:  GET

ticketaction_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:TicketAction:show" }
    methods:  GET

ticketaction_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:TicketAction:new" }
    methods:  [GET, POST]

ticketaction_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:TicketAction:edit" }
    methods:  [GET, POST]

ticketaction_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:TicketAction:delete" }
    methods:  DELETE
