unitresident_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:UnitResident:index" }
    methods:  GET

unitresident_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:UnitResident:show" }
    methods:  GET

unitresident_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:UnitResident:new" }
    methods:  [GET, POST]

unitresident_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:UnitResident:edit" }
    methods:  [GET, POST]

unitresident_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:UnitResident:delete" }
    methods:  DELETE
