unitinsurancepolicy_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:UnitInsurancePolicy:index" }
    methods:  GET

unitinsurancepolicy_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:UnitInsurancePolicy:show" }
    methods:  GET

unitinsurancepolicy_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:UnitInsurancePolicy:new" }
    methods:  [GET, POST]

unitinsurancepolicy_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:UnitInsurancePolicy:edit" }
    methods:  [GET, POST]

unitinsurancepolicy_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:UnitInsurancePolicy:delete" }
    methods:  DELETE
