unitmemo_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:UnitMemo:index" }
    methods:  GET

unitmemo_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:UnitMemo:show" }
    methods:  GET

unitmemo_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:UnitMemo:new" }
    methods:  [GET, POST]

unitmemo_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:UnitMemo:edit" }
    methods:  [GET, POST]

unitmemo_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:UnitMemo:delete" }
    methods:  DELETE
