unitgroup_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:UnitGroup:index" }
    methods:  GET

unitgroup_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:UnitGroup:show" }
    methods:  GET

unitgroup_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:UnitGroup:new" }
    methods:  [GET, POST]

unitgroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:UnitGroup:edit" }
    methods:  [GET, POST]

unitgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:UnitGroup:delete" }
    methods:  DELETE
