warehouse_index:
    path:     /
    defaults: { _controller: "HVGSystemBundle:Warehouse:index" }
    methods:  GET

warehouse_show:
    path:     /{id}/show
    defaults: { _controller: "HVGSystemBundle:Warehouse:show" }
    methods:  GET

warehouse_new:
    path:     /new
    defaults: { _controller: "HVGSystemBundle:Warehouse:new" }
    methods:  [GET, POST]

warehouse_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGSystemBundle:Warehouse:edit" }
    methods:  [GET, POST]

warehouse_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGSystemBundle:Warehouse:delete" }
    methods:  DELETE
