services:
    hvg_system.form.type.fileinput:
        class: HVG\SystemBundle\Form\UploadType
        arguments: ['@vich_uploader.storage', '@vich_uploader.upload_handler', '@translator']
        tags:
            - { name: form.type, alias: fileinput }
