HVG\SystemBundle\Entity\Person:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [rut]
    properties:
        rut:
            - NotBlank: ~
