user_security:
    resource: "@HVGUserBundle/Resources/config/routing/security.yml"

user_profile:
    resource: "@HVGUserBundle/Resources/config/routing/profile.yml"
    prefix: /profile

user_register:
    resource: "@HVGUserBundle/Resources/config/routing/registration.yml"
    prefix: /register

user_resetting:
    resource: "@HVGUserBundle/Resources/config/routing/resetting.yml"
    prefix: /resetting

user_change_password:
    resource: "@HVGUserBundle/Resources/config/routing/change_password.yml"
    prefix: /profile

user_manage:
    resource: "@HVGUserBundle/Resources/config/routing/manage.yml"
    prefix: /manage

