user_group_list:
    path:     /list
    defaults: { _controller: "HVGUserBundle:Profile:list" }
    methods: [GET]

user_group_new:
    path:     /new
    defaults: { _controller: "HVGUserBundle:Profile:new" }
    methods: [GET|POST]

user_group_show:
    path:     /{groupname}
    defaults: { _controller: "HVGUserBundle:Profile:show" }
    methods: [GET]

user_group_edit:
    path:     /{groupname}/edit
    defaults: { _controller: "HVGUserBundle:Profile:edit" }
    methods: [GET|POST]

user_group_delete:
    path:     /{groupname}/delete
    defaults: { _controller: "HVGUserBundle:Profile:delete" }
    methods: [GET]

