fos_user_profile_show:
    path:     /
    defaults: { _controller: "HVGUserBundle:Profile:show" }

fos_user_profile_edit:
    path:     /edit
    defaults: { _controller: "HVGUserBundle:Profile:edit" }
    methods: [GET|POST]
