exchange_ticket_index:
    path:     /index/{status}/{community}/{unitgroup}/{unit}
    defaults: { _controller: "HVGExchangeBundle:Ticket:index", status: '0', community: '', unitgroup: '', unit: '' }
    methods:  GET
    requirements:
        status: '\d+|'
        community: '\d+|'
        unitgroup: '\d+|'
        unit: '\d+|'

exchange_ticket_new:
    path:     /{unit}/new
    defaults: { _controller: "HVGExchangeBundle:Ticket:new" }
    methods:  [GET, POST]

exchange_ticket_show:
    path:     /{ticket}/show
    defaults: { _controller: "HVGExchangeBundle:Ticket:show" }
    methods:  GET

exchange_ticket_edit:
    path:     /{ticket}/edit
    defaults: { _controller: "HVGExchangeBundle:Ticket:edit" }
    methods:  [GET, POST]

exchange_ticket_delete:
    path:     /{ticket}/delete
    defaults: { _controller: "HVGExchangeBundle:Ticket:delete" }
    methods:  [GET, DELETE]

exchange_ticket_take:
    path:     /{ticket}/take
    defaults: { _controller: "HVGExchangeBundle:Ticket:take" }
    methods:  GET

exchange_ticket_release:
    path:     /{ticket}/release
    defaults: { _controller: "HVGExchangeBundle:Ticket:release" }
    methods:  GET

exchange_ticket_action:
    path:     /{ticket}/action
    defaults: { _controller: "HVGExchangeBundle:Ticket:action" }
    methods:  [GET, POST]

exchange_ticket_liability:
    path:     /{ticket}/liability
    defaults: { _controller: "HVGExchangeBundle:Ticket:liability" }
    methods:  [GET, POST]

exchange_ticket_status:
    path:     /{ticket}/status
    defaults: { _controller: "HVGExchangeBundle:Ticket:status" }
    methods:  [GET, POST]

exchange_ticket_test:
    path:     /{ticket}/test
    defaults: { _controller: "HVGExchangeBundle:Ticket:test" }
    methods:  [GET, POST]

