agent_carpark_index:
    path:     /{community}
    defaults: { _controller: "HVGAgentBundle:Carpark:index", community: '' }
    methods:  GET
    requirements:
        community: '\d+|'

agent_carpark_new:
    path:     /{community}/new
    defaults: { _controller: "HVGAgentBundle:Carpark:new" }
    methods:  [GET, POST]

agent_carpark_show:
    path:     /{carpark}/show
    defaults: { _controller: "HVGAgentBundle:Carpark:show" }
    methods:  GET

agent_carpark_edit:
    path:     /{carpark}/edit
    defaults: { _controller: "HVGAgentBundle:Carpark:edit" }
    methods:  [GET, POST]

agent_carpark_delete:
    path:     /{carpark}/delete
    defaults: { _controller: "HVGAgentBundle:Carpark:delete" }
    methods:  [GET, DELETE]
