agent_carpark_index:
    path:     /{community}/{unitgroup}/{unit}
    defaults: { _controller: "HVGAgentBundle:UnitResident:unit", community: '', unitgroup: '', unit: '' }
    methods:  GET
    requirements:
        community: '\d+|'
        unitgroup: '\d+|'
        unit: '\d+|'

agent_carpark_unitgroup:
    path:     /{id}/unitgroup
    defaults: { _controller: "HVGAgentBundle:UnitResident:unitgroup" }
    methods:  GET

agent_carpark_community:
    path:     /{id}/community
    defaults: { _controller: "HVGAgentBundle:UnitResident:community" }
    methods:  GET

agent_carpark_new:
    path:     /{unit}/new
    defaults: { _controller: "HVGAgentBundle:UnitResident:new" }
    methods:  [GET, POST]

agent_carpark_edit:
    path:     /{carpark}/edit
    defaults: { _controller: "HVGAgentBundle:UnitResident:edit" }
    methods:  [GET, POST]

agent_carpark_delete:
    path:     /{carpark}/delete
    defaults: { _controller: "HVGAgentBundle:UnitResident:delete" }
    methods:  DELETE
