agent_community_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:Community:index" }
    methods:  GET

agent_community_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Community:show" }
    methods:  GET
