agent_contact_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:Contact:index" }
    methods:  GET

agent_contact_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Contact:show" }
    methods:  GET

agent_contact_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:Contact:new" }
    methods:  [GET, POST]

agent_contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "HVGAgentBundle:Contact:edit" }
    methods:  [GET, POST]

agent_contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "HVGAgentBundle:Contact:delete" }
    methods:  DELETE
