agent_guest_index:
    path:     /{community}/{unitgroup}/{unit}
    defaults: { _controller: "HVGAgentBundle:UnitResident:unit", community: '', unitgroup: '', unit: '' }
    methods:  GET
    requirements:
        community: '\d+|'
        unitgroup: '\d+|'
        unit: '\d+|'

agent_guest_unitgroup:
    path:     /{id}/unitgroup
    defaults: { _controller: "HVGAgentBundle:UnitResident:unitgroup" }
    methods:  GET

agent_guest_community:
    path:     /{id}/community
    defaults: { _controller: "HVGAgentBundle:UnitResident:community" }
    methods:  GET

agent_guest_new:
    path:     /{unit}/new
    defaults: { _controller: "HVGAgentBundle:UnitResident:new" }
    methods:  [GET, POST]

agent_guest_edit:
    path:     /{guest}/edit
    defaults: { _controller: "HVGAgentBundle:UnitResident:edit" }
    methods:  [GET, POST]

agent_guest_delete:
    path:     /{guest}/delete
    defaults: { _controller: "HVGAgentBundle:UnitResident:delete" }
    methods:  DELETE
