agent_outflow_index:
    path:     /index
    defaults: { _controller: "HVGAgentBundle:Outflow:index" }
    methods:  GET

agent_outflow_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:Outflow:show" }
    methods:  GET

agent_outflow_new:
    path:     /new
    defaults: { _controller: "HVGAgentBundle:Outflow:new" }
    methods:  [GET, POST]

