agent_unitmemo_index:
    path:     /{community}/{unitgroup}/{unit}
    defaults: { _controller: "HVGAgentBundle:UnitMemo:index", community: '', unitgroup: '', unit: '' }
    methods:  GET
    requirements:
        community: '\d+|'
        unitgroup: '\d+|'
        unit: '\d+|'

agent_unitmemo_new:
    path:     /{unit}/new
    defaults: { _controller: "HVGAgentBundle:UnitMemo:new" }
    methods:  [GET, POST]

agent_unitmemo_show:
    path:     /{unitmemo}/show
    defaults: { _controller: "HVGAgentBundle:UnitMemo:show" }
    methods:  GET

agent_unitmemo_edit:
    path:     /{unitmemo}/edit
    defaults: { _controller: "HVGAgentBundle:UnitMemo:edit" }
    methods:  [GET, POST]

agent_unitmemo_delete:
    path:     /{unitmemo}/delete
    defaults: { _controller: "HVGAgentBundle:UnitMemo:delete" }
    methods:  [GET, DELETE]
