agent_unitgroup_index:
    path:     /
    defaults: { _controller: "HVGAgentBundle:UnitGroup:index" }
    methods:  GET

agent_unitgroup_show:
    path:     /{id}/show
    defaults: { _controller: "HVGAgentBundle:UnitGroup:show" }
    methods:  GET
